# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tartarus}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Insley"]
  s.date = %q{2009-11-24}
  s.description = %q{Provides exception logging and a generator for creating a clean interface to manage exceptions.}
  s.email = %q{dinsley@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/tartarus/USAGE",
     "generators/tartarus/tartarus_generator.rb",
     "generators/tartarus/templates/app/controllers/exceptions_controller.rb",
     "generators/tartarus/templates/app/models/logged_exception.rb",
     "generators/tartarus/templates/app/views/exceptions/_exception.html.erb",
     "generators/tartarus/templates/app/views/exceptions/details.html.erb",
     "generators/tartarus/templates/app/views/exceptions/index.html.erb",
     "generators/tartarus/templates/config/exceptions.yml",
     "generators/tartarus/templates/db/migrate/add_logged_exceptions.rb",
     "generators/tartarus/templates/public/javascripts/tartarus.jquery.js",
     "generators/tartarus/templates/public/stylesheets/tartarus.css",
     "generators/tartarus/templates/spec/controllers/exceptions_controller_spec.rb",
     "generators/tartarus/templates/spec/models/logged_exception_spec.rb",
     "lib/tartarus.rb",
     "lib/tartarus/logger.rb",
     "lib/tartarus/rescue.rb",
     "rails/init.rb",
     "spec/rails/app/controllers/application_controller.rb",
     "spec/rails/app/models/logged_exception.rb",
     "spec/rails/config/boot.rb",
     "spec/rails/config/database.yml",
     "spec/rails/config/environment.rb",
     "spec/rails/config/environments/development.rb",
     "spec/rails/config/environments/production.rb",
     "spec/rails/config/environments/test.rb",
     "spec/rails/config/exceptions.yml",
     "spec/rails/config/initializers/backtrace_silencers.rb",
     "spec/rails/config/initializers/inflections.rb",
     "spec/rails/config/initializers/mime_types.rb",
     "spec/rails/config/initializers/new_rails_defaults.rb",
     "spec/rails/config/initializers/session_store.rb",
     "spec/rails/config/locales/en.yml",
     "spec/rails/config/routes.rb",
     "spec/rails/db/test.sqlite3",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tartarus/logger_spec.rb",
     "spec/tartarus/rescue_spec.rb",
     "spec/tartarus_spec.rb",
     "tartarus.gemspec"
  ]
  s.homepage = %q{http://github.com/dinsley/tartarus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Exception Logging for Rails}
  s.test_files = [
    "spec/rails/app/controllers/application_controller.rb",
     "spec/rails/app/models/logged_exception.rb",
     "spec/rails/config/boot.rb",
     "spec/rails/config/environment.rb",
     "spec/rails/config/environments/development.rb",
     "spec/rails/config/environments/production.rb",
     "spec/rails/config/environments/test.rb",
     "spec/rails/config/initializers/backtrace_silencers.rb",
     "spec/rails/config/initializers/inflections.rb",
     "spec/rails/config/initializers/mime_types.rb",
     "spec/rails/config/initializers/new_rails_defaults.rb",
     "spec/rails/config/initializers/session_store.rb",
     "spec/rails/config/routes.rb",
     "spec/spec_helper.rb",
     "spec/tartarus/logger_spec.rb",
     "spec/tartarus/rescue_spec.rb",
     "spec/tartarus_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<will_paginate>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
    else
      s.add_dependency(%q<will_paginate>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<will_paginate>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
  end
end

